#!/usr/bin/env bash
# nws end-to-end overlay example (ROS / nix-ros-overlay).
#
# Runs, in ONE process (so the daemon stays alive the whole time):
#   1. start the nws daemon
#   2. create a temporary workspace folder
#   3. register it as an overlay workspace, pointing at this dir's resolver;
#      --dev-shell-packages asks nws to generate the ROS dev shell itself
#   4. clone a couple of TurtleBot repos into it
#   5. wait for nws to generate flake.nix
#   5b. switch the devShell to PATCH mode (nws manages the env binding; run.sh
#       adds the gazebo-GUI mesa/xcb shellHook — see inject_gui_layer below)
#   6. run `nix build` (bare)
#   7. HOLD; pressing Ctrl+C unregisters, stops the daemon and deletes the folder
#
# Philosophy: nws is GENERIC. It owns the marked nws block in the flake (the
# region between `# nws block — managed by nws; do not edit` and
# `# /nws block`: inputs, splice, packages.<system>, default — and now also
# devShells.<system>.default when the workspace registers with
# --dev-shell-packages). The dev shell is generated by nws itself in the
# standard nix-ros-overlay shape (mkShell + spliced0.buildEnv env over the
# same spliced inputs nws manages) with NO env-var shellHook — the packages'
# own setup hooks wire ROS_PACKAGE_PATH / GAZEBO_PLUGIN_PATH etc. Everything
# below the block's END marker stays ordinary USER content, byte-preserved
# across regenerations (a user devShell there takes precedence over nws's,
# fail-open).
#
# Use from the repo root's build artifacts:
#   from the project root:   result/bin/nws  (built via nix build .#main)

set -euo pipefail

# This script uses bashisms (local, $'\n', arrays). Running it via `sh run.sh`
# (dash) silently breaks the script. Require bash explicitly.
if [ -z "${BASH_VERSION:-}" ]; then
  echo "ERROR: run this script with bash:  bash $0" >&2
  exit 1
fi

# --- resolve paths relative to this script's location (no ~/gits hardcode) ---
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"          # examples/overlay-ros
ROOT="$HERE"
while [ ! -e "$ROOT/result/bin/nws" ] && [ "$ROOT" != "/" ]; do
  ROOT="$(dirname "$ROOT")"
done
NWS="$ROOT/result/bin/nws"                            # built binary
RESOLVER="$HERE/resolver.sh"                          # our package.xml mapper

PORT=17424
WS="/tmp/nws_example_overlay_ws"
DAEMON_LOG="/tmp/nws_example_overlay_daemon.log"

clean() {
  # disarm INT/TERM/EXIT while clean runs so a Ctrl+C during cleanup does not
  # re-trigger the trap (which caused an endless cascade of clean() calls).
  trap - INT TERM EXIT
  set +e
  echo "==> cleaning up (unregister + stop daemon + rm workspace)"
  "$NWS" unregister "$WS" </dev/null >/dev/null 2>&1
  pkill -f "$NWS service" 2>/dev/null
  rm -rf "$WS"
  pkill -f "$NWS service" 2>/dev/null
  exit 0
}
trap clean EXIT INT TERM

echo "==> nws binary: $NWS  (exists: $([ -e "$NWS" ] && echo yes || echo NO))"
[ -f "$NWS" ] || { echo "FATAL: $NWS missing — run 'nix build .#main' from the repo root first"; exit 1; }

# 1. start the daemon (fresh)
pkill -f "$NWS service" 2>/dev/null || true
sleep 0.3
"$NWS" service >"$DAEMON_LOG" 2>&1 &
SVC_PID=$!
for i in $(seq 1 50); do
  if printf 'LIST\n' | nc -w 1 127.0.0.1 "$PORT" >/dev/null 2>&1; then break; fi
  sleep 0.2
done
echo "==> daemon started (pid $SVC_PID)"

# 2+3. create + register the workspace (idempotent: unregister first if stale)
rm -rf "$WS"
mkdir -p "$WS"
"$NWS" unregister "$WS" </dev/null >/dev/null 2>&1 || true
"$NWS" register "$WS" \
  --overlay github:lopsided98/nix-ros-overlay/ros1-25.05 \
  --attr-path legacyPackages.x86_64-linux.noetic \
  --resolver "$RESOLVER" \
  --dev-shell-packages ros-base,gazebo-ros-pkgs,xacro,robot-state-publisher
#     ^ nws generates devShells.<system>.default itself: the standard
#       mkShell + spliced0.buildEnv pattern over the spliced children PLUS
#       these extra overlay attrs (ROS1 tooling + the gazebo stack;
#       gazebo-ros-pkgs is the metapackage that also brings gazebo-plugins —
#       the model plugins the URDF loads. xacro/robot-state-publisher are
#       undeclared launch-time deps of turtlebot3_gazebo).
echo "==> registered $WS"

# 4. clone repos.
# Exactly TWO clones:
#   - turtlebot3_simulations: the MAIN roslaunch package — provides
#     turtlebot3_gazebo with turtlebot3_empty_world.launch (starts gazebo).
#   - turtlebot3: the modifiable UNDERNEATH package — provides
#     turtlebot3_description (the URDF/xacro). Edit its materials/geometry and
#     the change is visible in the running gazebo simulation.
# Everything else (gazebo, gazebo_ros, xacro, robot_state_publisher, all msg/
# srv deps, the turtlebot3_msgs used by the model, ...) is pulled in
# automatically: the nix build downloads/builds those dependencies. Use the
# ROS1 `noetic` branches (ros1-25.05 pins ROS1/noetic; `master` is ROS2).
cd "$WS"
git clone --depth 1 --branch noetic https://github.com/ROBOTIS-GIT/turtlebot3_simulations.git turtlebot3-simulations
git clone --depth 1 --branch noetic https://github.com/ROBOTIS-GIT/turtlebot3.git turtlebot3
echo "==> cloned repos (noetic branches)"

# 5. wait for nws to discover the FULL clone set (this is the number of
# NAME<tab>RELPATH lines the resolver emits over the finished clones), so the
# generated flake splices every package — a partial set would silently fall
# back to upstream packages for the missing ones.
EXPECTED=$(bash "$RESOLVER" "$WS" | wc -l)
echo "==> resolver emits $EXPECTED packages; waiting for the daemon to splice them all..."
for i in $(seq 1 180); do
  HAVE=$(grep -c '= prev:' "$WS/flake.nix" 2>/dev/null || echo 0)
  if [ "$HAVE" -ge "$EXPECTED" ]; then break; fi
  # The daemon watches ONLY the workspace ROOT (inotify is not recursive):
  # deep file changes (touching package.xml inside a clone) wake nothing.
  # Touch the root's own flake.nix instead — an ATTRIB/CLOSE_WRITE event on
  # a root entry that always fires. Byte-equal skip makes it harmless.
  touch "$WS/flake.nix" 2>/dev/null || true
  sleep 0.5
  if [ $((i % 20)) -eq 0 ]; then echo "    ...$HAVE/$EXPECTED spliced so far"; fi
done
sleep 1   # let the daemon finish a regen after the last event
# force one final regeneration (full clone set present now)
touch "$WS/flake.nix" 2>/dev/null || true
sleep 1
echo "==> generated flake.nix"
sed -n '1,8p' "$WS/flake.nix"
grep -c '= prev:' "$WS/flake.nix" 2>/dev/null | xargs echo "    spliced children:"

###############################################################################
# 5b. USER GUI LAYER: switch the devShell into PATCH mode + gazebo-GUI fix.
#
# The nws-generated devShell is deliberately env-free (the packages' own setup
# hooks wire ROS_PACKAGE_PATH / GAZEBO_PLUGIN_PATH etc). But on hosts whose
# SYSTEM glibc is newer than the overlay pin's (e.g. NixOS after a system
# update), the gazebo GUI (gzclient) segfaults in OGRE: glvnd dlopens the
# system mesa, whose libgallium demands the newer glibc. The fix is a
# user-owned shellHook handing gzclient a closure-ABI mesa + the xcb Qt
# plugin — without disturbing nws's env generation.
#
# We append a USER devShell below the "# /nws block" END marker (so it
# survives regeneration) that carries the "# nws devShell block" markers; on
# the next sync nws stops emitting its own devShell attr and instead fills
# ONLY the marker region (PATCH mode) with the env binding, leaving our
# name/shellHook alone.
DEV_USER_MARK="# nws devShell block — managed by nws; do not edit"
inject_gui_layer() {
  local f="$WS/flake.nix"
  [ -f "$f" ] || return 1
  grep -qF "$DEV_USER_MARK" "$f" && return 0   # already switched to PATCH mode
  local user
  user="$(mktemp "$WS/.devshell-user.XXXXXX")"
  cat > "$user" <<'EONIX'
    devShells.x86_64-linux.default = let
      pkgsN = import inputs.nixpkgs { system = "x86_64-linux"; };
      # nws devShell block — managed by nws; do not edit
      # /nws devShell block
    in pkgsN.mkShell {
      name = "nws-dev-shell";
      packages = [ env ];
      shellHook = ''
        export LD_LIBRARY_PATH="${pkgsN.mesa}/lib"
        export LIBGL_DRIVERS_PATH="${pkgsN.mesa}/lib/dri"
        export QT_QPA_PLATFORM=xcb
      '';
    };
EONIX
  # insert below the "# /nws block" END marker (inside the outputs return set)
  sed "/^# \/nws block$/r $user" "$f" > "$f.tmp" && mv "$f.tmp" "$f"
  rm -f "$user"
  # let the daemon regenerate: it drops its own devShell attr and fills the
  # markers with the env binding (PATCH mode).
  touch "$f" 2>/dev/null || true
  for i in $(seq 1 40); do
    if ! grep -qF "$DEV_USER_MARK" "$f" 2>/dev/null; then break; fi
    if grep -q "env = spliced0.buildEnv" "$f" 2>/dev/null && [ "$(grep -c '^    devShells.x86_64-linux.default = let' "$f")" -eq 1 ]; then
      break
    fi
    sleep 0.5
  done
  if grep -q "env = spliced0.buildEnv" "$f" 2>/dev/null; then
    echo "==> devShell in PATCH mode — nws manages the env binding, run.sh owns the GUI shellHook"
  else
    echo "WARN: devShell PATCH-mode switch did not complete"
  fi
}
inject_gui_layer

# 6. build (bare; default output aggregates all spliced children) — best-effort.
# The default buildEnv aggregates every bare-spliced child; some monorepo
# subpackages have no declared deps and fail the debug-output split. That does
# NOT block the nws-generated dev shell (see the register step), so do NOT let
# a build failure abort the script (pipefail would) — `nix develop` is the
# point, and nws keeps the devShell's env buildable regardless.
#
# Insecure-package gate: turtlebot3_gazebo (a spliced child) depends on the
# gazebo stack, which needs nixpkgs' insecure `freeimage`. The gate lives in
# the OVERLAY's own nixpkgs import — flake-level `permittedInsecurePackages`
# cannot reach it. The documented nixpkgs mechanism is NIXPKGS_ALLOW_INSECURE
# + --impure, which every nixpkgs import in the eval honors. `nix develop`
# needs the same treatment (see the banner below).
cd "$WS"
echo "==> nix build ... (NIXPKGS_ALLOW_INSECURE=1 --impure: lifts the freeimage gate for the overlay's internal nixpkgs)"
set +e
NIXPKGS_ALLOW_INSECURE=1 nix build --impure --extra-experimental-features 'nix-command flakes' 2>&1 | tail -20
NIX_BUILD_EXIT=${PIPESTATUS[0]}
echo "==> nix build finished (exit $NIX_BUILD_EXIT) — continuing regardless"
set -e

# 7. everything is up — hand the workspace to the user.
# nws regenerates only its block on fs events, including the devShell it
# generated (devShells.<system>.default inside the block). User content below
# the "# /nws block" line is byte-preserved; a user devShell there takes
# precedence (nws logs and skips) — or the user can add the nws devShell block
# markers inside their own devShell to let nws manage its env binding.
echo
echo
echo "==> SUCCESS"
echo "==> Workspace ready at:    $WS"
echo "==> Daemon running (pid: $SVC_PID) — watching it for changes."
echo
echo "==> Run the GAZEBO simulation (see README):"
echo "    # The dev shell was generated by nws (standard nix-ros-overlay pattern,"
echo "    # no env-var shellHook — the packages' setup hooks do the wiring) and"
echo "    # then switched to PATCH mode: run.sh owns a small shellHook that adds a"
echo "    # closure-ABI mesa + xcb Qt so the gazebo GUI renders on newer-glibc hosts."
echo "    # The dev shell needs the same insecure-allow as the build:"
echo "    #   NIXPKGS_ALLOW_INSECURE=1 nix develop --impure"
echo "    # (the freeimage gate lives in the overlay's internal nixpkgs and can"
echo "    # only be lifted via the env var + --impure, not via flake content)"
echo "    export TURTLEBOT3_MODEL=burger   # or waffle / waffle_pi"
echo "    cd $WS && NIXPKGS_ALLOW_INSECURE=1 nix develop --impure   # into the ROS dev shell"
echo "    roscore                                 # terminal A: master"
echo "    roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch"
echo "        # terminal B: gazebo starts with the virtual turtlebot"
echo "    roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch"
echo "        # terminal C: drive it (arrow keys)"
echo "    roslaunch turtlebot3_gazebo turtlebot3_simulation.launch"
echo "        # terminal D: the simple test-drive node (turtlebot3_drive)"
echo "        # C++ nodes ship compiled inside the nws dev-shell env (built from"
echo "        # the LOCAL clones — the spliced src-overrides), so roslaunch"
echo "        # resolves them exactly like a built workspace."
echo
echo "==> The two local clones are: turtlebot3 (URDF/description) +"
echo "    turtlebot3_simulations (main gazebo launch). They are spliced"
echo "    (src-override) into every derivation, so the dev shell USES the local"
echo "    clones — URDF edits (e.g. a <material> colour in"
echo "    $WS/turtlebot3/turtlebot3_description/urdf/turtlebot3_burger.urdf.xacro)"
echo "    are visible in the running simulation."
echo "==> All other deps (gazebo, gazebo_ros, gazebo_plugins — the model"
echo "    plugins: diff drive / laser / imu that the URDF loads — xacro,"
echo "    robot_state_publisher, msgs, ...) are installed automatically;"
echo "    gazebo-ros-pkgs bundles gazebo-plugins, which is what makes /cmd_vel"
echo "    (and /odom, /scan) work in gazebo."
echo
echo "==> Press Ctrl+C to stop the daemon and delete the workspace."
while true; do
  sleep 3600
done
